from .client_API import client_interface

def setup_routes(app):
    app.router.add_route('GET', '/ping', client_interface.ping)
    app.router.add_route('GET', '/get_all_confs', client_interface.get_all_confs)
    app.router.add_route('GET', '/get_all_events', client_interface.get_all_events)
    app.router.add_route('GET' ,'/get_users_by_event', client_interface.get_users_by_event)
    app.router.add_route('GET' ,'/get_users_remind_by_event', client_interface.get_users_remind_by_event)
    app.router.add_route('GET', '/get_event_name', client_interface.get_event_name)
    app.router.add_route('GET', '/get_event_descr', client_interface.get_event_descr)
    app.router.add_route('GET', '/get_event_url', client_interface.get_event_url)
    app.router.add_route('GET', '/get_event_date', client_interface.get_event_date)
    app.router.add_route('GET', '/get_event_theme', client_interface.get_event_theme)
    app.router.add_route('GET', '/get_subconf_by_conf_event', client_interface.get_subconf_by_conf_event)
    app.router.add_route('GET', '/get_conf_options', client_interface.get_conf_options)
    app.router.add_route('GET', '/get_conf_themes', client_interface.get_conf_themes)
    app.router.add_route('POST', '/set_options_for_conf', client_interface.set_options_for_conf)
    app.router.add_route('POST', '/set_themes_for_conf', client_interface.set_themes_for_conf)
    app.router.add_route('POST', '/set_subconf_for_conf_event', client_interface.set_subconf_for_conf_event)
    app.router.add_route('POST', '/set_user_for_event', client_interface.set_user_for_event)
    app.router.add_route('POST', '/set_user_remind_for_event', client_interface.set_user_remind_for_event)
    app.router.add_route('POST', '/add_conf', client_interface.add_conf)
    app.router.add_route('DELETE', '/del_user_for_event', client_interface.del_user_for_event)
    app.router.add_route('DELETE', '/del_user_remind_for_event', client_interface.del_user_remind_for_event)